# on configuration.yaml

notify:
  - name: TvOverlayNotify
    platform: rest
    method: POST_JSON
    resource: http://[ip]:[port]/notify 
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}" # string | main text | default: null
      appTitle: "{{ data.appTitle  | default('Home Assistant') }}" # string | extra info text | default: null
      color: "{{ data.color | default('#049cdb') }}" # string | color tint for smallIcon. accepts 6 or 8 digit color hex. the '#' is optional | default: null
      image: "{{ data.image | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      video: "{{ data.video | default(null) }}" # string | video url. supports rtps, hls, dash, smoothstreaming | default: null
      smallIcon: "{{ data.smallIcon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      largeIcon: "{{ data.largeIcon | default(null) }}" # string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
      corner: "{{ data.corner  | default(null) }}" # string | position on the screen. accept values: bottom_start, bottom_end, top_start, top_end | default: null (uses hot corner)
      seconds: "{{ data.seconds | default(null) }}" # int | duration that the notification will stay visible in seconds | default: null (uses duration setting)
      
  - name: TvOverlayNotifyFixed
    platform: rest
    method: POST_JSON
    resource: http://[ip]:[port]/notify_fixed
    verify_ssl: false
    title_param_name: title
    data:
      id: "{{ data.id | default(null) }}"
      text: "{{ data.text  | default(null) }}"
      icon: "{{ data.icon | default(null) }}"
      textColor: "{{ data.textColor | default(null) }}"
      iconColor: "{{ data.iconColor | default(null) }}"
      borderColor: "{{ data.borderColor | default(null) }}"
      backgroundColor: "{{ data.backgroundColor | default(null) }}"
      shape: "{{ data.shape | default(null) }}"
      visible: "{{ data.visible | default(true) }}"
      expiration: "{{ data.expiration | default(null) }}"

      
rest_command:
  tvoverlay:
    url: http://[ip]:[port]/set/overlay
    method: POST
    verify_ssl: false
    headers:
      accept: 'application/json'
    content_type:  'application/json; charset=utf-8'
    payload: '{{ payload }}'
