# Generic home assistant SCRIPT to send a notification

alias: Rest notification test
sequence:
  - service: notify.tvoverlaysample
    data:
      data:
        id: "notification_sample" # optional id string - if a notification is being displayed and the tvoverlay receives a notification with the same id, the notification displayed is updated instantly
        appTitle: AppTitle # optional text field
        appIcon: mdi:unicorn  # optional - accepts mdi icons, image urls and Bitmap encoded to Base64
        color: "#FFF000" # optional - accepts 6 or 8 digit color hex. the '#' is optional
        smallIcon: mdi:speaker-multiple # optional - accepts mdi icons, image urls and Bitmap encoded to Base64
        largeIcon: mdi:camera # optional - accepts mdi icons, image urls and Bitmap encoded to Base64
        corner: bottom_end  # optional - values: bottom_start, bottom_end, top_start, top_end
        seconds: 7  # optional - exibition duration
      message: This is my message to you! # REQUIRED: this is a required field for home assistant, but it can be 'null' if not needed
      title: Here is a Title  # optional text field
mode: single

# Use case 1: Notify on person arriving Home (AUTOMATION)

alias: Person online notification
trigger:
  - platform: state
    entity_id:
      - person.person1
      - person.person2
    to: home
    from: not_home
condition: []
action:
  - service: notify.tvoverlaysuite
    data:
      data:
        smallIcon: mdi:home
        color: "#008000"
        largeIcon: [home_assistant_external_url]{{ trigger.from_state.attributes.entity_picture }}
      message: >-
        {{ trigger.from_state.attributes.friendly_name }} is Home
mode: single

# Use case 2: Notify with image, when a motion is detect in a camera

alias: Motion notification
trigger:
  - type: motion # For the trigger, I selected my camera device on the UI, and it had an option for 'Motion started detecting motion'
    platform: device
    device_id: [device_id]
    entity_id: [device_id]
    domain: binary_sensor
condition: []
action:
  - service: notify.tvoverlaysuite
    data:
      message: Motion detect at Front door!
      data:
        image: >-
          [home_assistant_external_url]{{ state_attr('camera.[CAMERA]',
          'entity_picture')+'&time='}}{{as_timestamp(now())}} 
          # home_assistant_external_url is my https url for my home assistant. 
          # entity_picture is a parial url to the camera still image, like '/api/camera_proxy/camera.[CAMERA}?token=XXX'.
          # I added a timestamp simply to avoid the image being cached.
        color: "#B00020"
        largeIcon: mdi:motion-sensor
        smallIcon: mdi:camera
        seconds: 10
mode: single
