# Generic home assistant SCRIPT to send a notification

alias: Rest notification test
sequence:
  - service: notify.tvoverlaysample
    data:
      title: Here is a Title  # optional | string | main text | default: null
      message: This is my message to you! # REQUIRED: this is a required field for home assistant, but it can be 'null' if not needed | string | secondary text | default: null
      data:
        id: "notification_sample" # optional | string | can be used to edit a notification while in queue or being displayed | default: [random]
        appTitle: AppTitle # optional | string | extra info text | default: null
        smallIcon: mdi:speaker-multiple # optional | string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
        color: "#FFF000" # optional | string | color tint for smallIcon. accepts 6 or 8 digit color hex. the '#' is optional | default: null
        largeIcon: mdi:camera # optional | string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
        corner: bottom_end  # optional | string | position on the screen. accept values: bottom_start, bottom_end, top_start, top_end | default: null (uses hot corner)
        seconds: 7  # optional | int | duration that the notification will stay visible in seconds | default: null (uses duration setting)
        image: "https://fastly.picsum.photos/id/778/300/300.jpg"  # optional | string | accepts mdi icons, image urls and Bitmap encoded to Base64 | default: null
        video: "rtsp://localhost:5555/live"  # optional | string | video url. supports rtps, hls, dash, smoothstreaming | default: null
mode: single

# Use case 1: Notify on person arriving Home (AUTOMATION)

alias: Person online notification
trigger:
  - platform: state
    entity_id:
      - person.person1
      - person.person2
    to: home
    from: not_home
condition: []
action:
  - service: notify.tvoverlaysuite
    data:
      data:
        smallIcon: mdi:home
        color: "#008000"
        largeIcon: [home_assistant_external_url]{{ trigger.from_state.attributes.entity_picture }} # home_assistant_external_url is my https url for my home assistant. 
      message: >-
        {{ trigger.from_state.attributes.friendly_name }} is Home
mode: single

# Use case 2: Notify with image, when a motion is detect in a camera

alias: Motion notification
trigger:
  - type: motion # For the trigger, I selected my camera device on the UI, and it had an option for 'Motion started detecting motion'
    platform: device
    device_id: [device_id]
    entity_id: [device_id]
    domain: binary_sensor
condition: []
action:
  - service: notify.tvoverlaysuite
    data:
      message: Motion detect at Front door!
      data:
        image: >-
          [home_assistant_external_url]{{ state_attr('camera.[CAMERA]',
          'entity_picture')+'&time='}}{{as_timestamp(now())}} 
          # home_assistant_external_url is my https url for my home assistant. 
          # entity_picture is a parial url to the camera still image, like '/api/camera_proxy/camera.[CAMERA}?token=XXX'.
          # I added a timestamp simply to avoid the image being cached.
        color: "#B00020"
        largeIcon: mdi:motion-sensor
        smallIcon: mdi:camera
        seconds: 10
mode: single
